### ISSUE TITLE
Why Node and TsLint path on server side

### ISSUE THREAD

**Issue by TristanFAURE** [Pablissimo/SonarTsPlugin#136]
Hello,
I've tested this plugin for sonar and it seems quite interesting.

I've followed instructions on this page : https://github.com/Pablissimo/SonarTsPlugin
and I don't understand why node should be install on server and why tslint path must be fill as the rules are analyzed locally.

Can you explain me please ?

**Comment by Pablissimo** [comment]
Node doesn't have to be installed on the server, just has to be on whatever is doing the analysis (which is itself sometimes the same box as the machine hosting SonarQube, depending on your setup).

Being able to set the config path at a server level lets you (in an enterprise setting) use a single reference analysis rule set for multiple projects, from a network share or some source controlled repository for example.

**Comment by TristanFAURE** [comment]
Ok thank you for the details according to my english level it was not clear on the documentation (sorry about that !).

Ok so if the ts path is not referenced at server side, tslint is searched locally inside the npm registry ?

**Comment by Pablissimo** [comment]
Sorry, just deleted a comment about the tslint path because it was misleading - there are also some situations where you may want to ensure the same version of tslint is used for analysing all projects, in some enterprise settings. 

You don't *have* to do this, you just can. Typically the path to tslint is auto-detected by the plugin in the node_modules folder, but you can override this in your sonar-project.properties file if it can't find it. Run the scanner with the -X flag and it'll tell you where it's searching for things and, if it goes wrong, give hints as to why.

**Comment by TristanFAURE** [comment]
OK thanks, i can close this issue !
