### ISSUE TITLE
No issues are find out 

### ISSUE THREAD

**Issue by Nagarjunaavula** [Pablissimo/SonarTsPlugin#18]
I have installed this plugin on Sona 4.5.1 version. When i run my project by setting the language as ts i am not seeing any issues. Attached screen shot will explain the issue. Please provide the solution for this.
![ts_issue](https://cloud.githubusercontent.com/assets/655820/13285037/47f3f890-db1e-11e5-95ef-7c5f26551009.png)

**Comment by Pablissimo** [comment]
Can you run sonar-runner with the -X -e options, please? And dump the output to a file - it'll give you diagnostic info that may help figure out what's going on. Typically this happens when the path to TsLint hasn't been specified correctly.

**Comment by drywolf** [comment]
Hi,
I just had a look at the hosted demo projects and I can't see any issues or technical debt there either...

![image](https://cloud.githubusercontent.com/assets/394294/14294406/3ded1660-fb71-11e5-88cc-243d2af5871e.png)

Is this just a thing about the demos, or is it related to this issue ?

**Comment by Pablissimo** [comment]
Several annoyingly are too clean to have any issues (by their own tslint rules), and the technical debt figure being zero is due to issue #9 as none of the issues raised have any time component associated with them.

Try the TypeScript Compiler project (click through to it [comme ça](https://sonar.pablissimo.com/overview?id=18739)) which at least has issues reported.

I didn't want to do those projects a disservice by applying a 'default' tslint.json rule configuration to them, but had I done so the results would be **way** more interesting so perhaps I'll ... tweak their own style guides...

**Comment by drywolf** [comment]
Thanks for clearing that up, yeah probably some configuration that actually shows some issues is better suited for demonstration purposes (including a disclaimer that the shown debt is just for demo purposes to not insult the demo project maintainers) :smile:

I just tried out the plugin on one of my projects and it works pretty well. One thing I'm still trying ot figure out tho is if a custom rule that I have in my rules-dir is included in the dashboards or not. I saw that support for rules-dir has been added, but is this only to be able to run the scanner or are the custom rules also handled on the sonarqube server side ?

Thanks for sharing this plugin :+1:

**Comment by Pablissimo** [comment]
So custom rules are run properly (you'd see failures when running ````sonar-runner```` otherwise - try adding a 'fake' rule definition to your ````tslint.json```` and you'll see what I mean). However - the plugin doesn't know about them, so can't yet advertise them to SonarQube with 'proper' rule names. I'll create an issue for that because it's pretty annoying.

They should show up with whatever message your custom rule reports to TsLint and therefore appear in SonarQube, but the 'category' of rule breach ends up being a generic bucket for all unknown rule breaches.

**Comment by Pablissimo** [comment]
Opened #24 for that.

**Comment by Pablissimo** [comment]
Ah, actually the TypeScript Compiler project comes to the rescue again - it has [several custom rule breaches](https://sonar.pablissimo.com/component_issues?id=TypeScript#resolved=false|rules=tslint%3Atslint-issue) that appear.

**Comment by drywolf** [comment]
Cool ... I think I just figured out that the custom rule that I was looking for is actually only relevant for .tsx files in my project, but .tsx files seem not to be included in the scanning of the project ... does the plugin not treat .tsx yet ?

**Comment by Pablissimo** [comment]
Nope, never come across one before - raise an issue!

**Comment by drywolf** [comment]
I created a PR (#25) for the .tsx support, with that in place I can see some of my custom rules working, but one in particular still does not seem to show up. I will create an issue once I have done some more debugging on what could be happening there.

**Comment by Pablissimo** [comment]
Without further info from the OP there's not much more to do here, closing but happy to reopen if specific info forthcoming.
