### ISSUE TITLE
Javascript LCOV files

### ISSUE THREAD

**Issue by bluntspoon** [Pablissimo/SonarTsPlugin#50]
Firstly welldone on a great plugin.

I have a large typescript project, with karma unit tests. And I currently use this plugin to do Linting of my TS files. I'm now trying to add the karma generated LCOV report to the process, but running into issues.

Does your LCOV parser support reading of LCOV files generated off javascript files. The report is generated and read in correctly by Teamcity. But as soon as I pump it into the Sonar it doesn't yeild any results.

Any help with this is appreciated. 
Andrew

**Comment by Pablissimo** [comment]
So - the LCOV file needs to be translated via a sourcemap to point back to your TypeScript files (since multiple lines of TypeScript may transpile out to a single line of JS, or vice-versa, it's the only way to get accurate line-level coverage). Now there's an open issue surronding this: #48 which I'm not sure about.

If you've already done the conversion and are seeing problems, you've probably got what #48's got - otherwise you'll need to re-map your LCOV back to TypeScript files for the plugin to use the data.

**Comment by bluntspoon** [comment]
Thanks, was wondering if your plugin would report on the JS version of the LCOV. If not I'll have to setup the Istanbul-remap step.

**Comment by Pablissimo** [comment]
Sadly not, to do so would require it to understand sourcemaps which I guess could be looked at as an enhancement.



Sent from a mobile device - apologies for any errors as a result


-------- Original message --------

**Comment by rodikal** [comment]
@bluntspoon take a look at https://www.npmjs.com/package/karma-remap-istanbul

**Comment by Pablissimo** [comment]
Closing as a workaround exists, and pulling in more deps to parse sourcemaps doesn't seem like the right way to approach this one.
