### ISSUE TITLE
code smell issues are not showing in sonar Qube using tslintplugin for Angular2 project

### ISSUE THREAD

**Issue by sujatha1d** [Pablissimo/SonarTsPlugin#68]
Line of code alone is coming. code smell issues are not coming for my angular2 project using TSlint plugin in SONAR Qube

sonar.projectKey=test
sonar.projectName=test
sonar.projectVersion=1.0
sonar.language=ts
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.ts.excludetypedefinitionfiles=true
#sonar.ts.tslintpath=node_modules/tslint
sonar.ts.tslintconfigpath=/src/tslint.json
# Optional
sonar.exclusions=/node_modules/**/*,**/*/*.spec.ts,**/*.spec.ts,**/*.d.ts

**Comment by Pablissimo** [comment]
So: 

- If you run tslint at the command line with the tslint.json file you've supplied, do you get any breaches?
- Can you run the sonar-runner with -X -e arguments please, and post the logs?

**Comment by gozumi** [comment]
I am getting this issue too.

I created the following deliberate errors in my code

`var j = 0;`
`if (j == 0) {`
  `    eval('var i = 0');`
`}`

When I run tslint using this command

`tslint --project tslint.json`

I get the following listing errors

`src/main.ts[17, 5]: forbidden eval`
`src/main.ts[14, 1]: Forbidden 'var' keyword, use 'let' or 'const' instead`
`src/main.ts[16, 7]: == should be ===`

The contents of my  _sonar-project.properties_ file is 

`sonar.projectKey=<project key>`
`sonar.projectName=<project name>`
`sonar.projectVersion=1.0`
`sonar.sources=src/app`
`sonar.ts.lcov.reportpath=reports/coverage/lcov.info`
`sonar.ts.tslintconfigpath=tslint.json`
`sonar.sourceEncoding=UTF-8`
`sonar.web.port=9006`

When I execute

`sonar-sanner`

I do not get any code smells appearing in the sonarqube report. I would expect the code smells to highlight the same listing errors that the tslint command picks up.

**Comment by gozumi** [comment]
Here is the output after running sonar-scanner.

$ sonar-scanner -X -e
10:28:52.926 INFO: Option -e/--errors is no longer supported and will be ignored
10:28:52.939 INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/2.8/libexec/conf/sonar-scanner.properties
10:28:52.940 INFO: Project root configuration file: /Users/iana/Developmemt/gozumi/london-tube-live/sonar-project.properties
10:28:52.956 INFO: SonarQube Scanner 2.8
10:28:52.956 INFO: Java 1.8.0_92 Oracle Corporation (64-bit)
10:28:52.957 INFO: Mac OS X 10.12.2 x86_64
10:28:53.080 DEBUG: keyStore is :
10:28:53.080 DEBUG: keyStore type is : jks
10:28:53.080 DEBUG: keyStore provider is :
10:28:53.080 DEBUG: init keystore
10:28:53.081 DEBUG: init keymanager of type SunX509
10:28:53.097 INFO: User cache: /Users/iana/.sonar/cache
10:28:53.097 DEBUG: Extract sonar-scanner-api-batch in temp...
10:28:53.108 DEBUG: Get bootstrap index...
10:28:53.108 DEBUG: Download: http://localhost:9006/batch_bootstrap/index
10:28:53.177 DEBUG: Get bootstrap completed
10:28:53.177 DEBUG: Create isolated classloader...
10:28:53.190 DEBUG: Start temp cleaning...
10:28:53.207 DEBUG: Temp cleaning done
10:28:53.207 DEBUG: Execution getVersion
10:28:53.214 DEBUG: Execution start
10:28:53.473 DEBUG: Publish global mode
10:28:53.584 INFO: Load global repositories
10:28:53.632 DEBUG: GET 200 http://localhost:9006/batch/global | time=43ms
10:28:53.692 INFO: Load global repositories (done) | time=108ms
10:28:53.709 INFO: User cache: /Users/iana/.sonar/cache
10:28:53.929 INFO: Load plugins index
10:28:53.933 DEBUG: GET 200 http://localhost:9006/deploy/plugins/index.txt | time=4ms
10:28:53.933 INFO: Load plugins index (done) | time=4ms
10:28:53.934 DEBUG: Load plugins
10:28:53.947 DEBUG: Load plugins (done) | time=13ms
10:28:53.959 DEBUG: API compatibility mode is enabled on plugin Git [scmgit] (built with API lower than 5.2)
10:28:53.961 DEBUG: API compatibility mode is enabled on plugin SVN [scmsvn] (built with API lower than 5.2)
10:28:54.074 DEBUG: Plugins:
10:28:54.075 DEBUG:   * C# 5.5.1.522 (csharp)
10:28:54.075 DEBUG:   * Java 4.3.0.7717 (java)
10:28:54.077 DEBUG:   * Git 1.2 (scmgit)
10:28:54.077 DEBUG:   * TypeScript 0.98-SNAPSHOT (typescript)
10:28:54.077 DEBUG:   * SVN 1.3 (scmsvn)
10:28:54.077 DEBUG:   * JavaScript 2.18.0.3454 (javascript)
10:28:54.097 DEBUG: Execution getVersion
10:28:54.097 INFO: SonarQube server 6.1
10:28:54.097 INFO: Default locale: "en_GB", source code encoding: "UTF-8"
10:28:54.098 DEBUG: Work directory: /Users/iana/Developmemt/gozumi/london-tube-live/.sonar
10:28:54.098 DEBUG: Execution getVersion
10:28:54.098 DEBUG: Execution execute
10:28:54.446 INFO: Process project properties
10:28:54.449 DEBUG: Process project properties (done) | time=3ms
10:28:54.559 INFO: Load project repositories
10:28:54.576 DEBUG: GET 200 http://localhost:9006/batch/project.protobuf?key=gozumi%3Alondon-tube-live | time=16ms
10:28:54.657 INFO: Load project repositories (done) | time=98ms
10:28:54.724 DEBUG: Available languages:
10:28:54.725 DEBUG:   * C# => "cs"
10:28:54.725 DEBUG:   * Java => "java"
10:28:54.725 DEBUG:   * TypeScript => "ts"
10:28:54.725 DEBUG:   * JavaScript => "js"
10:28:54.728 INFO: Load quality profiles
10:28:54.767 DEBUG: GET 200 http://localhost:9006/api/qualityprofiles/search.protobuf?projectKey=gozumi%3Alondon-tube-live | time=39ms
10:28:54.771 INFO: Load quality profiles (done) | time=44ms
10:28:54.775 INFO: Load active rules
10:28:54.810 DEBUG: GET 200 http://localhost:9006/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=cs-sonar-way-13715&p=1&ps=500 | time=35ms
10:28:54.938 DEBUG: GET 200 http://localhost:9006/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=java-sonar-way-21077&p=1&ps=500 | time=86ms
10:28:54.963 DEBUG: GET 200 http://localhost:9006/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=js-sonar-way-36433&p=1&ps=500 | time=19ms
10:28:54.982 DEBUG: GET 200 http://localhost:9006/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=ts-tslint-16035&p=1&ps=500 | time=16ms
10:28:54.996 INFO: Load active rules (done) | time=221ms
10:28:55.029 INFO: Publish mode
10:28:55.030 DEBUG: Start recursive analysis of project modules
10:28:55.031 INFO: -------------  Scan London Tube Live
10:28:55.118 INFO: Load server rules
10:28:55.137 DEBUG: GET 200 http://localhost:9006/api/rules/list.protobuf | time=18ms
10:28:55.146 INFO: Load server rules (done) | time=28ms
10:28:55.219 DEBUG: Initializers :
10:28:55.219 INFO: Base dir: /Users/iana/Developmemt/gozumi/london-tube-live
10:28:55.219 INFO: Working dir: /Users/iana/Developmemt/gozumi/london-tube-live/.sonar
10:28:55.220 INFO: Source paths: src/app
10:28:55.220 INFO: Source encoding: UTF-8, default locale: en_GB
10:28:55.221 INFO: Index files
10:28:55.225 DEBUG: Declared extensions of language C# were converted to sonar.lang.patterns.cs : **/*.cs
10:28:55.225 DEBUG: Declared extensions of language Java were converted to sonar.lang.patterns.java : **/*.java,**/*.jav
10:28:55.225 DEBUG: Declared extensions of language TypeScript were converted to sonar.lang.patterns.ts : **/*.ts,**/*.tsx
10:28:55.225 DEBUG: Declared extensions of language JavaScript were converted to sonar.lang.patterns.js : **/*.js
10:28:55.228 DEBUG: Language of file 'src/app/app.component.ts' is detected to be 'ts'
10:28:55.229 DEBUG: Language of file 'src/app/app.module.ts' is detected to be 'ts'
10:28:55.229 DEBUG: Language of file 'src/app/app.routing.ts' is detected to be 'ts'
10:28:55.230 DEBUG: Language of file 'src/app/data/actions/index.ts' is detected to be 'ts'
10:28:55.230 DEBUG: Language of file 'src/app/data/actions/post.ts' is detected to be 'ts'
10:28:55.230 DEBUG: Language of file 'src/app/data/data.module.ts' is detected to be 'ts'
10:28:55.231 DEBUG: Language of file 'src/app/data/models/journey.interface.ts' is detected to be 'ts'
10:28:55.240 DEBUG: Language of file 'src/app/data/reducers/index.ts' is detected to be 'ts'
10:28:55.240 DEBUG: Language of file 'src/app/data/store/store.service.ts' is detected to be 'ts'
10:28:55.240 DEBUG: Language of file 'src/app/data/reducers/posts.ts' is detected to be 'ts'
10:28:55.240 DEBUG: Language of file 'src/app/features/features.module.ts' is detected to be 'ts'
10:28:55.240 DEBUG: Language of file 'src/app/data/store/test/store.fixture.ts' is detected to be 'ts'
10:28:55.240 DEBUG: Language of file 'src/app/data/store/test/store.service.spec.ts' is detected to be 'ts'
10:28:55.240 DEBUG: Language of file 'src/app/data/util/index.ts' is detected to be 'ts'
10:28:55.241 DEBUG: Language of file 'src/app/features/features.routing.ts' is detected to be 'ts'
10:28:55.242 DEBUG: Language of file 'src/app/features/overview/overview.component.ts' is detected to be 'ts'
10:28:55.242 DEBUG: Language of file 'src/app/index.ts' is detected to be 'ts'
10:28:55.243 DEBUG: Language of file 'src/app/services/auth/auth.module.ts' is detected to be 'ts'
10:28:55.242 DEBUG: Language of file 'src/app/features/overview/test/overview.component.spec.ts' is detected to be 'ts'
10:28:55.242 DEBUG: Language of file 'src/app/features/overview/test/overview.fixture.ts' is detected to be 'ts'
10:28:55.246 DEBUG: Language of file 'src/app/services/live-data-stream/live-data-stream.service.ts' is detected to be 'ts'
10:28:55.244 DEBUG: Language of file 'src/app/services/auth/test/auth.service.spec.ts' is detected to be 'ts'
10:28:55.244 DEBUG: Language of file 'src/app/services/auth/test/auth.fixture.ts' is detected to be 'ts'
10:28:55.243 DEBUG: Language of file 'src/app/services/auth/auth.service.ts' is detected to be 'ts'
10:28:55.251 DEBUG: Language of file 'src/app/services/live-data-stream/test/live-data-stream.fixture.ts' is detected to be 'ts'
10:28:55.251 DEBUG: Language of file 'src/app/services/live-data-stream/test/live-data-stream.service.spec.ts' is detected to be 'ts'
10:28:55.251 DEBUG: Language of file 'src/app/test/app.component.fixture.ts' is detected to be 'ts'
10:28:55.252 DEBUG: Language of file 'src/app/test/app.component.spec.ts' is detected to be 'ts'
10:28:55.255 INFO: 28 files indexed
10:28:55.265 INFO: Quality profile for ts: TsLint
10:28:55.269 DEBUG: Code colorizer, supported languages:
10:28:55.677 DEBUG: 'C#' skipped because there is no related file in current project
10:28:55.678 DEBUG: 'SurefireSensor' skipped because there is no related file in current project
10:28:55.678 DEBUG: 'JaCoCoSensor' skipped because there is no related file in current project
10:28:55.678 DEBUG: 'JaCoCoItSensor' skipped because there is no related file in current project
10:28:55.678 DEBUG: 'JaCoCoOverallSensor' skipped because there is no related file in current project
10:28:55.679 DEBUG: 'JavaSquidSensor' skipped because there is no related file in current project
10:28:55.679 DEBUG: 'JavaScript Squid Sensor' skipped because there is no related file in current project
10:28:55.687 DEBUG: Sensors : Lines Sensor -> SCM Sensor -> Coverage Report Import -> Coverage Report Import -> Unit Test Results Import -> XmlFileSensor -> Linting sensor for TypeScript files -> Combined LCOV and LOC sensor -> Zero Coverage Sensor -> Code Colorizer Sensor -> CPD Block Indexer
10:28:55.687 INFO: Sensor Lines Sensor
10:28:55.703 INFO: Sensor Lines Sensor (done) | time=16ms
10:28:55.703 INFO: Sensor SCM Sensor
10:28:55.723 INFO: SCM provider for this project is: git
10:28:55.728 INFO: 3 files to be analyzed
10:28:55.754 DEBUG: readpipe [git, --version],/usr/local/bin
10:28:55.780 DEBUG: readpipe may return 'git version 2.9.2'
10:28:55.781 DEBUG: remaining output:

10:28:55.781 DEBUG: readpipe [git, config, --system, --edit],/usr/local/bin
10:28:55.803 DEBUG: readpipe may return '/usr/local/etc/gitconfig'
10:28:55.803 DEBUG: remaining output:

10:28:55.838 DEBUG: Blame file src/app/services/live-data-stream/live-data-stream.service.ts
10:28:55.838 DEBUG: Blame file src/app/services/live-data-stream/test/live-data-stream.fixture.ts
10:28:55.838 DEBUG: Blame file src/app/services/live-data-stream/test/live-data-stream.service.spec.ts
10:28:55.968 DEBUG: Unable to blame file src/app/services/live-data-stream/live-data-stream.service.ts. No blame info at line 1. Is file committed? [Author: PersonIdent[Not Committed Yet, , Thu Dec 29 10:28:55 2016 +0000] Source commit: null]
10:28:55.968 DEBUG: Unable to blame file src/app/services/live-data-stream/test/live-data-stream.fixture.ts. No blame info at line 1. Is file committed? [Author: PersonIdent[Not Committed Yet, , Thu Dec 29 10:28:55 2016 +0000] Source commit: null]
10:28:55.968 DEBUG: Unable to blame file src/app/services/live-data-stream/test/live-data-stream.service.spec.ts. No blame info at line 1. Is file committed? [Author: PersonIdent[Not Committed Yet, , Thu Dec 29 10:28:55 2016 +0000] Source commit: null]
10:28:55.970 INFO: 0/3 files analyzed
10:28:55.970 WARN: Missing blame information for the following files:
10:28:55.970 WARN:   * /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/live-data-stream/test/live-data-stream.service.spec.ts
10:28:55.970 WARN:   * /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/live-data-stream/live-data-stream.service.ts
10:28:55.970 WARN:   * /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/live-data-stream/test/live-data-stream.fixture.ts
10:28:55.970 WARN: This may lead to missing/broken features in SonarQube
10:28:55.970 INFO: Sensor SCM Sensor (done) | time=267ms
10:28:55.970 INFO: Sensor Coverage Report Import
10:28:55.971 DEBUG: No coverage property. Skip Sensor
10:28:55.971 INFO: Sensor Coverage Report Import (done) | time=1ms
10:28:55.971 INFO: Sensor Coverage Report Import
10:28:55.971 DEBUG: No coverage property. Skip Sensor
10:28:55.971 INFO: Sensor Coverage Report Import (done) | time=0ms
10:28:55.971 INFO: Sensor Unit Test Results Import
10:28:55.971 DEBUG: No unit test results property. Skip Sensor
10:28:55.971 INFO: Sensor Unit Test Results Import (done) | time=0ms
10:28:55.971 INFO: Sensor XmlFileSensor
10:28:55.972 INFO: Sensor XmlFileSensor (done) | time=1ms
10:28:55.972 INFO: Sensor Linting sensor for TypeScript files
10:28:55.973 DEBUG: Path sonar.ts.tslintpath not specified, falling back to node_modules/tslint/bin/tslint
10:28:55.973 DEBUG: Found sonar.ts.tslintconfigpath Lint path to be 'tslint.json'
10:28:55.973 DEBUG: Path sonar.ts.tslintrulesdir not specified, falling back to null
10:28:55.975 DEBUG: Using a temporary path for TsLint output: /Users/iana/Developmemt/gozumi/london-tube-live/.sonar/.sonartmp/5500154083982610633.tmp
10:28:55.977 DEBUG: Split 28 files into 1 batches for processing
10:28:55.978 DEBUG: Executing TsLint with command: node /Users/iana/Developmemt/gozumi/london-tube-live/node_modules/tslint/bin/tslint --format json --out /Users/iana/Developmemt/gozumi/london-tube-live/.sonar/.sonartmp/5500154083982610633.tmp --config /Users/iana/Developmemt/gozumi/london-tube-live/tslint.json /Users/iana/Developmemt/gozumi/london-tube-live/src/app/app.component.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/app.module.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/app.routing.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/actions/index.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/actions/post.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/data.module.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/models/journey.interface.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/reducers/index.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/reducers/posts.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/store/store.service.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/store/test/store.fixture.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/store/test/store.service.spec.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/util/index.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/features/features.module.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/features/features.routing.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/features/overview/overview.component.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/features/overview/test/overview.component.spec.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/features/overview/test/overview.fixture.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/index.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/auth/auth.module.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/auth/auth.service.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/auth/test/auth.fixture.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/auth/test/auth.service.spec.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/live-data-stream/live-data-stream.service.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/live-data-stream/test/live-data-stream.fixture.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/live-data-stream/test/live-data-stream.service.spec.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/test/app.component.fixture.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/test/app.component.spec.ts
10:28:57.654 INFO: Sensor Linting sensor for TypeScript files (done) | time=1682ms
10:28:57.654 INFO: Sensor Combined LCOV and LOC sensor
10:28:57.675 INFO: Analysing /Users/iana/Developmemt/gozumi/london-tube-live/reports/coverage/lcov.info
10:28:57.694 DEBUG: Default value of zero will be saved for file: src/app/app.module.ts
10:28:57.694 DEBUG: Because was not present in LCOV report.
10:28:57.695 DEBUG: Default value of zero will be saved for file: src/app/app.routing.ts
10:28:57.695 DEBUG: Because was not present in LCOV report.
10:28:57.696 DEBUG: Default value of zero will be saved for file: src/app/data/actions/index.ts
10:28:57.696 DEBUG: Because was not present in LCOV report.
10:28:57.698 DEBUG: Default value of zero will be saved for file: src/app/data/data.module.ts
10:28:57.698 DEBUG: Because was not present in LCOV report.
10:28:57.699 DEBUG: Default value of zero will be saved for file: src/app/data/models/journey.interface.ts
10:28:57.699 DEBUG: Because was not present in LCOV report.
10:28:57.700 DEBUG: Default value of zero will be saved for file: src/app/data/store/test/store.service.spec.ts
10:28:57.700 DEBUG: Because was not present in LCOV report.
10:28:57.702 DEBUG: Default value of zero will be saved for file: src/app/features/features.module.ts
10:28:57.702 DEBUG: Because was not present in LCOV report.
10:28:57.703 DEBUG: Default value of zero will be saved for file: src/app/features/features.routing.ts
10:28:57.703 DEBUG: Because was not present in LCOV report.
10:28:57.704 DEBUG: Default value of zero will be saved for file: src/app/features/overview/test/overview.component.spec.ts
10:28:57.704 DEBUG: Because was not present in LCOV report.
10:28:57.705 DEBUG: Default value of zero will be saved for file: src/app/index.ts
10:28:57.705 DEBUG: Because was not present in LCOV report.
10:28:57.705 DEBUG: Default value of zero will be saved for file: src/app/services/auth/auth.module.ts
10:28:57.706 DEBUG: Because was not present in LCOV report.
10:28:57.708 DEBUG: Default value of zero will be saved for file: src/app/services/auth/test/auth.service.spec.ts
10:28:57.708 DEBUG: Because was not present in LCOV report.
10:28:57.709 DEBUG: Default value of zero will be saved for file: src/app/services/live-data-stream/test/live-data-stream.fixture.ts
10:28:57.709 DEBUG: Because was not present in LCOV report.
10:28:57.710 DEBUG: Default value of zero will be saved for file: src/app/services/live-data-stream/test/live-data-stream.service.spec.ts
10:28:57.710 DEBUG: Because was not present in LCOV report.
10:28:57.711 DEBUG: Default value of zero will be saved for file: src/app/test/app.component.spec.ts
10:28:57.711 DEBUG: Because was not present in LCOV report.
10:28:57.711 INFO: Sensor Combined LCOV and LOC sensor (done) | time=57ms
10:28:57.711 INFO: Sensor Zero Coverage Sensor
10:28:57.733 INFO: Sensor Zero Coverage Sensor (done) | time=22ms
10:28:57.733 INFO: Sensor Code Colorizer Sensor
10:28:57.735 INFO: Sensor Code Colorizer Sensor (done) | time=2ms
10:28:57.735 INFO: Sensor CPD Block Indexer
10:28:57.735 INFO: DefaultCpdBlockIndexer is used for ts
10:28:57.735 DEBUG: No CpdMapping for language ts
10:28:57.735 INFO: Sensor CPD Block Indexer (done) | time=0ms
10:28:57.736 INFO: Calculating CPD for 0 files
10:28:57.736 INFO: CPD calculation finished
10:28:57.863 INFO: Analysis report generated in 116ms, dir size=43 KB
10:28:57.948 INFO: Analysis reports compressed in 85ms, zip size=40 KB
10:28:57.948 INFO: Analysis report generated in /Users/iana/Developmemt/gozumi/london-tube-live/.sonar/batch-report
10:28:57.948 DEBUG: Upload report
10:28:57.983 DEBUG: POST 200 http://localhost:9006/api/ce/submit?projectKey=gozumi:london-tube-live&projectName=London%20Tube%20Live | time=33ms
10:28:57.986 INFO: Analysis report uploaded in 37ms
10:28:57.986 INFO: ANALYSIS SUCCESSFUL, you can browse http://localhost:9006/dashboard/index/gozumi:london-tube-live
10:28:57.986 INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
10:28:57.986 INFO: More about the report processing at http://localhost:9006/api/ce/task?id=AVlKICXqL1yoOFRX28Qj
10:28:57.992 DEBUG: Report metadata written to /Users/iana/Developmemt/gozumi/london-tube-live/.sonar/report-task.txt
10:28:57.992 DEBUG: Post-jobs :
10:28:57.995 INFO: Task total time: 3.892 s
10:28:57.996 INFO: ------------------------------------------------------------------------
10:28:57.996 INFO: EXECUTION SUCCESS
10:28:57.996 INFO: ------------------------------------------------------------------------
10:28:57.996 INFO: Total time: 5.063s
10:28:58.091 INFO: Final Memory: 53M/286M
10:28:58.091 INFO: ------------------------------------------------------------------------
10:28:58.091 DEBUG: Execution getVersion
10:28:58.092 DEBUG: Execution stop

**Comment by Pablissimo** [comment]
So if you run ```tslint``` against main.ts (with your deliberate error), but use the ```--config``` instead of ```--project``` option, do you get output? Note that the plugin doesn't supply the ```--project``` flag to tslint (yet), but it shouldn't be required for linting.

The log above suggests things are working OK, really - to double-check, also try:

    node /Users/iana/Developmemt/gozumi/london-tube-live/node_modules/tslint/bin/tslint --format json --config /Users/iana/Developmemt/gozumi/london-tube-live/tslint.json /Users/iana/Developmemt/gozumi/london-tube-live/src/main.ts 

You should get output for your deliberately erroneous file. If you don't, suggests that tslint.json isn't configured right.

**Comment by gozumi** [comment]
If I run 

`tslint --config tslint.json`

I get the following output

`Usage: tslint [options] file ...`

`Options:`
 ` -c, --config          configuration file`
 ` --force               return status code 0 even if there are lint errors`
 ` -h, --help            display detailed help`
 ` -i, --init            generate a tslint.json config file in the current working directory`
 ` -o, --out             output file`
 ` -r, --rules-dir       rules directory`
 ` -s, --formatters-dir  formatters directory`
 ` -e, --exclude         exclude globs from path expansion`
 ` -t, --format          output format (prose, json, stylish, verbose, pmd, msbuild, checkstyle, vso)  [default: "prose"]`
`  --test                test that tslint produces the correct output for the specified directory`
 ` --project             tsconfig.json file`
 ` --type-check          enable type checking when linting a project`
 ` -v, --version         current version`

`Missing files`

I assume I am doing something wrong???

**Comment by gozumi** [comment]
My bad.

I ran it again like this

`tslint --config tslint.json src/main.ts`

and I get the following output

`src/main.ts[16, 5]: forbidden eval`
`src/main.ts[14, 1]: Forbidden 'var' keyword, use 'let' or 'const' instead`
`src/main.ts[15, 7]: == should be ===`

**Comment by Pablissimo** [comment]
You need to include the path to a file to analyse - you get that for free (ish) when using the --project parameter, but without it you need the path to main.ts to follow as the last argument.

**Comment by gozumi** [comment]
Just figured that out - see my comment above.

**Comment by Pablissimo** [comment]
Cool - so things look to be configured correctly (good news!). Next up - take the whole command line that's in the logs and run it, removing the '--out' parameter. The following should do the trick:

    node /Users/iana/Developmemt/gozumi/london-tube-live/node_modules/tslint/bin/tslint --format json --config /Users/iana/Developmemt/gozumi/london-tube-live/tslint.json /Users/iana/Developmemt/gozumi/london-tube-live/src/app/app.component.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/app.module.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/app.routing.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/actions/index.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/actions/post.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/data.module.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/models/journey.interface.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/reducers/index.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/reducers/posts.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/store/store.service.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/store/test/store.fixture.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/store/test/store.service.spec.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/data/util/index.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/features/features.module.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/features/features.routing.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/features/overview/overview.component.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/features/overview/test/overview.component.spec.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/features/overview/test/overview.fixture.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/index.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/auth/auth.module.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/auth/auth.service.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/auth/test/auth.fixture.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/auth/test/auth.service.spec.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/live-data-stream/live-data-stream.service.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/live-data-stream/test/live-data-stream.fixture.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/services/live-data-stream/test/live-data-stream.service.spec.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/test/app.component.fixture.ts /Users/iana/Developmemt/gozumi/london-tube-live/src/app/test/app.component.spec.ts

Do you get json output to the console with actual failures?

**Comment by gozumi** [comment]
When I run that command I get the following output

`[]%`

**Comment by Pablissimo** [comment]
So - something funky there then. That's suggesting that tslint's not seeing *any* issues with your code. I notice that main.ts, your file with deliberate errors, isn't in the set that's being analysed. If you tack it into the end of the command line as an extra path, do you get output?

**Comment by gozumi** [comment]
Thanks for the help - You spotted the problem. Turns out my issue was down to user error.

I had the following config in my _sonar-project.properties_ file

`sonar.sources=src/app`

This was exploding the _src/main.ts_ file from analysis.

When I changed this setting to 

`sonar.sources=src`

The code smells were reported correctly in sonarqube. Thanks for your time in helping me with this.

**Comment by Pablissimo** [comment]
Hooray! Not a prob,

**Comment by Pablissimo** [comment]
(Also congrats on having such clean code as to not have any lint issues!)

**Comment by gozumi** [comment]
lol :-)
